apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rbp-tar
  name: rbp-tar-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem